jobs:
    build:
      docker:
        - image: sillelien/circleci-dollar-build-image

      environment:
        MAJOR_VERSION: 0.3
        NEXT_MAJOR_VERSION: 0.4
        MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM} "
        TZ: "/usr/share/zoneinfo/Europe/London"

      working_directory: ~/dollar-parent

      branches:
        ignore:
          - gh-pages

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: init
            command: /home/circleci/.build-init.sh

        - run:
            name: dependencies
            command: |
              ~/build-utils/maven_make_deps.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2
        - run:
            name: test
            command: |
                 mvn -q -T 1C -Drat.skip -Dsource.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true integration-test
            no_output_timeout: 600

        - deploy:
            command: |
              if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                      ~/build-utils/promote_from_staging.sh
              fi
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      ~/build-utils/maven_deploy.sh
              fi
